### ISSUE TITLE
您好，请问macOS运行start.sh出现以下报错怎么处理呢？

### ISSUE THREAD

**Issue by jackhexiangyu12** [poor-circle/XMU-Daily-Reporter#1]
错误代码：./start.sh: line 2: ./daily_reporter: Permission denied
<img width="481" alt="截屏2021-09-13 下午9 57 28" src="https://user-images.githubusercontent.com/87466111/133096922-01f45cfe-5d8d-4eff-96de-37c75e81a027.png">

请问您这个daily_reporter文件是用什么语言编写的呀？mac似乎不能直接打开这个文件运行

**Comment by poor-circle** [comment]
你下载的是linux版本，自然不能在macos上面跑。
daily_reporter是可执行的二进制程序，不能跨操作系统执行。
如果你想要运行这个程序的话，需要自己用cmake在macos上编译源代码

**Comment by poor-circle** [comment]
./daily_reporter: Permission denied

你要给daily_report加权限，让他可以执行。不过在macos上面，他也跑不动的。

**Comment by poor-circle** [comment]
作者手上只有win机器和linux机器，所以目前没办法帮你提供一个macos下面编译好的版本

**Comment by jackhexiangyu12** [comment]
哦哦，好的，我知道了，原来mac和linux的软件也不是完全通用的，要自己编译一遍，谢谢您了，学长辛苦了
