### ISSUE TITLE
您好，请问支持打卡多人吗，要如何编写配置呢？

### ISSUE THREAD

**Issue by lovemaoli** [poor-circle/XMU-Daily-Reporter#2]

**Comment by poor-circle** [comment]
目前不支持。如果需要多人打卡，你可以注册多个账号。多人打卡的功能支持计划于2.1版本中更新。

**Comment by lovemaoli** [comment]
Big bang! Your mail to QIN Guoyang has been thrown into his mailbox. He will pick up your mail and read it through ASAP, and reply if needed.嘣！您的邮件已经投入我家邮筒了，我会尽快取出来阅读。如果需要回信，我会尽快亲笔给您回信。

**Comment by lovemaoli** [comment]
好的 谢谢您
