### ISSUE TITLE
学长您好，请问为啥会爆空指针错误呢

### ISSUE THREAD

**Issue by GoatYoung** [poor-circle/XMU-Daily-Reporter#7]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/41860150/200228981-5463598d-6d20-4969-abf6-63f8b9a5ef2b.png">

**Comment by poor-circle** [comment]
个人信息填对了吗

**Comment by poor-circle** [comment]
```
{
    "xmu": {
        "ID": "23320779999999",
        "password": "123456"
    }
}
```
仔细核对一下格式是不是按这个来的

**Comment by GoatYoung** [comment]
> 

是正确的，学长，我今天中午反复尝试了好多次还是不行，刚刚也尝试了一次也是不行。之前都是可以的，就这几天突然崩了

**Comment by poor-circle** [comment]
我这也没看到你之前的action啊，都是今天的

**Comment by GoatYoung** [comment]
我今天把之前的删了，想着重新配置也许可以解决，但是没有成功

**Comment by poor-circle** [comment]
> 我今天把之前的删了，想着重新配置也许可以解决，但是没有成功

你下一个本地版本的程序，看看会不会出问题

**Comment by poor-circle** [comment]
https://github.com/poor-circle/XMU-Daily-Reporter/releases

**Comment by poor-circle** [comment]
如果本地没问题的话我弄个调试版的程序看看在线版本是崩在哪里了

**Comment by GoatYoung** [comment]
学长，我本地测了，没问题

**Comment by poor-circle** [comment]
> 学长，我本地测了，没问题

我更新了程序，你重新运行一下看看是什么错误

**Comment by poor-circle** [comment]
> 学长，我本地测了，没问题

运行之前记得先从主线把新的程序同步你的分支，不然跑的还是旧的程序

**Comment by poor-circle** [comment]
> 学长，我本地测了，没问题

![image](https://user-images.githubusercontent.com/51276909/200268800-4130c931-1219-4dc9-bac8-4d313dad01a5.png)

**Comment by GoatYoung** [comment]
/home/runner/work/_temp/28fd6265-a3ca-46d9-b8e4-f617b41de77b.sh: line 4:  1644 Segmentation fault      (core dumped) ./daily_reporter
[10](https://github.com/GoatYoung/XMU-Daily-Reporter/actions/runs/3408962334/jobs/5670155376#step:3:11)
Error: Process completed with exit code 139.
依旧是这个错误....

**Comment by poor-circle** [comment]
奇怪，怎么连一行日志都没输出就挂了

**Comment by poor-circle** [comment]
我看几个别人fork出去的打卡，好像也没有这个问题啊

**Comment by poor-circle** [comment]
@GoatYoung 已修复，你可以再试试了

**Comment by poor-circle** [comment]
> @GoatYoung 已修复，你可以再试试了

我的二进制文件是静态链接的，不过由于glibc不能完全静态链接，似乎在高版本ubuntu下会报错。强制指定运行的ubuntu版本为20.04可修复该问题。
