### ISSUE TITLE
sleep Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

### ISSUE THREAD

**Issue by 17816712353** [poor-circle/XMU-Daily-Reporter#8]
[sleep](https://github.com/17816712353/XMU-Daily-Reporter/actions/runs/3558197646/jobs/5976704667)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

呜呜呜，这是啥意思呀？

**Comment by poor-circle** [comment]
Fixed. github 的checkout@v2已过时，脚本已升级到checkout@v3
